import { P } from "./permissions.js";

export const ROLE_PERMISSIONS = Object.freeze({
  admin: Object.freeze(["*"]),
  piercer: Object.freeze([
    P.DASHBOARD_VIEW, P.APPOINTMENTS_VIEW, P.APPOINTMENTS_CREATE, P.APPOINTMENTS_EDIT, P.APPOINTMENTS_RESCHEDULE,
    P.APPOINTMENTS_CANCEL, P.APPOINTMENTS_REVIEW, P.APPOINTMENTS_FINALIZE, P.APPOINTMENTS_APPLY_DISCOUNT,
    P.APPOINTMENTS_APPLY_COUPON, P.APPOINTMENTS_EDIT_FINAL_VALUE, P.CLIENTS_VIEW, P.CLIENTS_CREATE, P.CLIENTS_EDIT,
    P.ANAMNESIS_VIEW, P.ANAMNESIS_EDIT, P.ANAMNESIS_REVIEW, P.CLINICAL_FILES_VIEW, P.CLINICAL_FILES_EDIT,
    P.SALES_VIEW, P.SALES_CREATE, P.SALES_EDIT_OPEN, P.INVENTORY_VIEW, P.INVENTORY_SELL, P.INVENTORY_ADJUST,
    P.CASH_VIEW, P.CASH_OPEN, P.CASH_RECEIVE_PAYMENT, P.CASH_CLOSE,
    P.COMMUNICATION_VIEW, P.COMMUNICATION_SEND, P.COUPONS_VIEW, P.COUPONS_APPLY, P.SETTINGS_VIEW
  ]),
  reception: Object.freeze([
    P.DASHBOARD_VIEW, P.APPOINTMENTS_VIEW, P.APPOINTMENTS_CREATE, P.APPOINTMENTS_EDIT, P.APPOINTMENTS_RESCHEDULE,
    P.APPOINTMENTS_CANCEL, P.APPOINTMENTS_APPLY_DISCOUNT, P.APPOINTMENTS_APPLY_COUPON, P.CLIENTS_VIEW, P.CLIENTS_CREATE,
    P.CLIENTS_EDIT, P.ANAMNESIS_VIEW, P.ANAMNESIS_EDIT, P.SALES_VIEW, P.SALES_CREATE, P.SALES_EDIT_OPEN,
    P.INVENTORY_VIEW, P.INVENTORY_SELL, P.CASH_VIEW, P.CASH_OPEN, P.CASH_RECEIVE_PAYMENT,
    P.COMMUNICATION_VIEW, P.COMMUNICATION_SEND, P.COUPONS_VIEW, P.COUPONS_APPLY, P.SETTINGS_VIEW
  ]),
  finance: Object.freeze([
    P.DASHBOARD_VIEW, P.DASHBOARD_FINANCIAL, P.APPOINTMENTS_VIEW, P.CLIENTS_VIEW, P.SALES_VIEW, P.SALES_EDIT_CLOSED,
    P.SALES_CANCEL, P.INVENTORY_VIEW, P.INVENTORY_VIEW_COST, P.CASH_VIEW, P.CASH_OPEN, P.CASH_RECEIVE_PAYMENT,
    P.CASH_CLOSE, P.CASH_WITHDRAW, P.CASH_ADJUST, P.FINANCE_VIEW, P.FINANCE_CREATE, P.FINANCE_EDIT,
    P.FINANCE_CANCEL, P.FINANCE_MARK_TEST, P.FINANCE_EXPENSES, P.FINANCE_REFUND, P.REPORTS_VIEW_FINANCIAL,
    P.COMMISSION_VIEW_ALL, P.AUDIT_VIEW, P.SETTINGS_VIEW
  ])
});
